/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime false cloudflare-env.d.ts` (hash: 47be3bd997b42b65bda8c612fac56e47)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	DEMO_MODE: "true" | "false";
	DATABASE_DRIVER: "d1";
	REQUIRE_JWT_SECRET: "true" | "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface PreviewEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		DEMO_MODE: "true";
		DATABASE_DRIVER: "d1";
		REQUIRE_JWT_SECRET: "true";
	}
	interface ProductionEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		DEMO_MODE: "false";
		DATABASE_DRIVER: "d1";
		REQUIRE_JWT_SECRET: "true";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEMO_MODE" | "DATABASE_DRIVER" | "REQUIRE_JWT_SECRET">> {}
}
